on:
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          python3 ./prebuild/make_static_schedule.py
