on:
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:

jobs:
  update-static-schedule:
    name: Update Static Schedule
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          cd prebuild && python3 ./make_static_schedule.py

      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
